// Pop scouting candidate data.
// Compiled from public trade press, editorial "artists to watch" features,
// niche music newsletters (Hear Hear and One Write Music, full archives reviewed
// 2026-08-18), DIY Magazine's weekly Neu Bulletin, Notion Magazine's weekly
// Undiscovered series, and Spotify's public artist pages (logged-out).
// Not a live feed yet — see README for the plan to wire this to a real API.

const ARTISTS = [
  // ---- Qualifies: under 1M single streams AND under 100K monthly listeners ----
  {
    name: "Sung Holly",
    genre: "Bedroom Pop",
    monthlyListeners: 37007,
    topTrackStreams: 196810,
    topTrack: "Only Takes One",
    status: "qualifies",
    signal: "Debut single produced by Rostam (ex-Vampire Weekend). 74K TikTok / 100K IG, no public label info found.",
    source: "Hear Hear (Substack)",
    sourceUrl: "https://hearhear.substack.com/p/7-rising-artists-to-know-in-2026",
    spotifyUrl: "https://open.spotify.com/artist/0z4BrD9oXnSUhUd80zLgCL",
    checkedAt: "2026-08-18"
  },
  {
    name: "Dottie Andersson",
    genre: "Garage Pop",
    monthlyListeners: 72425,
    topTrackStreams: null,
    topTrack: "Only metaphorically",
    status: "qualifies",
    signal: "Swedish artist, bright garage-pop. Praised by Northern Transmissions for 'contradiction done right.'",
    source: "Hear Hear (Substack)",
    sourceUrl: "https://hearhear.substack.com/p/7-rising-artists-to-know-in-2026",
    spotifyUrl: "https://open.spotify.com/artist/360qeHf7kan9K9bKFPNwVM",
    checkedAt: "2026-08-18"
  },
  {
    name: "Eileen Alister",
    genre: "Pop",
    monthlyListeners: 90860,
    topTrackStreams: 735360,
    topTrack: "Lifetime Lover",
    status: "qualifies",
    signal: "23-year-old Swiss singer-songwriter, moody dark-pop edge. First headline tour sold out within hours (small European venues). Signed to indie label H2 Music Records — not majors.",
    source: "Rolling Stone UK",
    sourceUrl: "https://www.rollingstone.co.uk/music/rolling-stone-uk-future-of-music-2026-full-list-61467/",
    spotifyUrl: "https://open.spotify.com/artist/2XPubfqZp6J4uEEJop2OL2",
    checkedAt: "2026-08-18"
  },
  {
    name: "LOLITAH",
    genre: "Femme Pop",
    monthlyListeners: 15640,
    topTrackStreams: 377330,
    topTrack: "Bounce",
    status: "qualifies",
    signal: "London-based, reshaping femme pop through vulnerability and cinematic storytelling. Debut EP earned praise from NME, I-D, and BBC Radio 1. Fully self-released, no label.",
    source: "Hear Hear (Substack) — Essential Summer 2026 playlists",
    sourceUrl: "https://hearhear.substack.com/p/essential-summer-2026-playlists",
    spotifyUrl: "https://open.spotify.com/artist/4VljXOkEAZ4EWzvbvJszyT",
    checkedAt: "2026-08-18"
  },
  {
    name: "reiko",
    genre: "Hyperpop",
    monthlyListeners: 72669,
    topTrackStreams: 98865,
    topTrack: "paraknowya",
    status: "qualifies",
    signal: "Hyperpop artist becoming more prominent as the subgenre edges into the mainstream. Self-released under her own imprint (REGALIA // callreiko).",
    source: "One Write Music (Substack) — 'For A Good Time - Call Reiko'",
    sourceUrl: "https://onewritemusic.substack.com/archive",
    spotifyUrl: "https://open.spotify.com/artist/1swF0fjO1rWmJEbygzTpf2",
    checkedAt: "2026-08-18"
  },
  {
    name: "AmiiFy",
    genre: "Indie Pop / R&B",
    monthlyListeners: 89137,
    topTrackStreams: 712704,
    topTrack: "Ways",
    status: "qualifies",
    signal: "Nigerian-born, self-taught producer (BandLab on his phone) blending funkadelic, indie pop/rock and R&B. 'Ways' got real TikTok traction. Fully self-released.",
    source: "One Write Music (Substack) — 'Numb Before You Notice'",
    sourceUrl: "https://onewritemusic.substack.com/archive",
    spotifyUrl: "https://open.spotify.com/artist/0gdCxcoEObSShoJ3HayPnJ",
    checkedAt: "2026-08-18"
  },
  {
    name: "acloudyskye",
    genre: "Bedroom Pop / Dream Pop",
    monthlyListeners: 59920,
    topTrackStreams: 513717,
    topTrack: "To tell you the truth",
    status: "qualifies",
    signal: "One-person bedroom project, minimal public presence. Sits in the same lane as wishlane / Glacier / tsubi club (Spotify's own 'fans also like' cluster). Self-released.",
    source: "One Write Music (Substack) — 'A Place Where Mountains Hide'",
    sourceUrl: "https://onewritemusic.substack.com/archive",
    spotifyUrl: "https://open.spotify.com/artist/5OeSHuvHTS9qUgAUTt3GIR",
    checkedAt: "2026-08-18"
  },
  {
    name: "Kate Stephenson",
    genre: "Pop",
    monthlyListeners: 91739,
    topTrackStreams: 271161,
    topTrack: "Summerfoot",
    status: "qualifies",
    signal: "Illinois singer-songwriter, genre-bending pop. Indie-distributed (Many Hats Distribution), not a major. CAUTION: already booked on a 21-date European tour (with Fairhazel) — likely has booking representation already, worth confirming before approach.",
    source: "One Write Music (Substack) — 'The Reckoning in Kate's Most Recent Release'",
    sourceUrl: "https://onewritemusic.substack.com/archive",
    spotifyUrl: "https://open.spotify.com/artist/5RAwXhLQfEX5khIsfnvDne",
    checkedAt: "2026-08-18"
  },
  {
    name: "Lauren Auder",
    genre: "Alt-Pop",
    monthlyListeners: 53473,
    topTrackStreams: 124663,
    topTrack: "yes",
    status: "qualifies",
    signal: "British-French singer/producer. Touring small European clubs (Le Hasard Ludique, Brudenell Social Club). Released on small imprint untitled (recs).",
    source: "Hear Hear (Substack) — Essential Summer 2026 playlists",
    sourceUrl: "https://hearhear.substack.com/p/essential-summer-2026-playlists",
    spotifyUrl: "https://open.spotify.com/artist/5rxf4rjZ5lyhKt7DWM5dLL",
    checkedAt: "2026-08-18"
  },
  {
    name: "The Cindys",
    genre: "Power Pop",
    monthlyListeners: 5751,
    topTrackStreams: 4793,
    topTrack: "Glass Shattered",
    status: "qualifies",
    signal: "Bristol outfit making retro-tinged power pop — DIY called 'Glass Shattered' a certified earworm. Released on tiny UK label Breakfast Records. Extremely early.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/feature/the-neu-bulletin-sailor-honeymoon-the-cindys-june-mcdoom-and-more",
    spotifyUrl: "https://open.spotify.com/artist/6O0qcs3kv0stMY583BavCx",
    checkedAt: "2026-08-18"
  },
  {
    name: "Sesame Girl",
    genre: "Bedroom Pop / Dream Pop",
    monthlyListeners: 43092,
    topTrackStreams: 143911,
    topTrack: "Back To Texas",
    status: "qualifies",
    signal: "Australian, dreamy bedroom-pop aesthetic. Playing small local venues (cafes, bars) around Sydney/Canberra.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/feature/the-neu-bulletin-sailor-honeymoon-the-cindys-june-mcdoom-and-more",
    spotifyUrl: "https://open.spotify.com/artist/1M0AUiCvSkRu9wBC3z2wBX",
    checkedAt: "2026-08-18"
  },
  {
    name: "Alfreda",
    genre: "Art Pop",
    monthlyListeners: 3859,
    topTrackStreams: 39782,
    topTrack: "Patsy",
    status: "qualifies",
    signal: "London-based art-pop artist, theatrical/camp persona. 'Patsy' co-written with The xx's Oliver Sim. Independently distributed via AWAL, no label. Extremely early.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/feature/the-neu-bulletin-theatre-essence-martins-chloe-slater-and-more",
    spotifyUrl: "https://open.spotify.com/artist/57HS6X4QpZkt1JeT7QpNcM",
    checkedAt: "2026-08-18"
  },
  {
    name: "Essence Martins",
    genre: "Alt-Pop / Soul",
    monthlyListeners: 61163,
    topTrackStreams: 618793,
    topTrack: "Sleepless",
    status: "qualifies",
    signal: "British-Nigerian, folk-tinged alt-pop blending organic and synth textures. Currently on a UK support tour (O2 Institute3, KOKO), not headlining.",
    source: "DIY Magazine — The Neu Bulletin / 'Get to Know...' feature",
    sourceUrl: "https://diymag.com/feature/the-neu-bulletin-theatre-essence-martins-chloe-slater-and-more",
    spotifyUrl: "https://open.spotify.com/artist/4DahLnNm7J5zRiQmiQeWec",
    checkedAt: "2026-08-18"
  },
  {
    name: "samxemma",
    genre: "Electro-Pop / Dance-Pop",
    monthlyListeners: 16833,
    topTrackStreams: 527137,
    topTrack: "HOT BOYS MAKE HOT MUSIC",
    status: "qualifies",
    signal: "Sits in the same 'fans also like' cluster as Rose Gray and Empress Of — genuine dance-pop/electro-pop lane. Small indie licensing deal (September Recordings Ltd), not a major.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/3t0tkWfZvQbKkmji8oa26y",
    checkedAt: "2026-08-18"
  },
  {
    name: "KuleeAngee",
    genre: "R&B / Neo-Soul Pop",
    monthlyListeners: 31219,
    topTrackStreams: 329972,
    topTrack: "Animated Love",
    status: "qualifies",
    signal: "Playing small European club dates (Sebright Arms, PARIS 12). Released via small indie label (Underplay / LAB Records).",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/7u56IQStytIQ51gm5haOeM",
    checkedAt: "2026-08-18"
  },
  {
    name: "Lucas Geddes",
    genre: "Pop / R&B",
    monthlyListeners: 12804,
    topTrackStreams: 881293,
    topTrack: "Can't Get Over",
    status: "qualifies",
    signal: "London-born vocalist, multi-instrumentalist, and producer. Fully self-released.",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },
  {
    name: "Fran Lusty",
    genre: "Folk-Pop",
    monthlyListeners: 3973,
    topTrackStreams: 429341,
    topTrack: "Brother",
    status: "qualifies",
    signal: "Featured in Indie/Pop/Folk compilations by alexrainbirdMusic. Charming, self-taught singer-songwriter profile.",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },
  {
    name: "False Idah",
    genre: "Alt-Pop",
    monthlyListeners: 248,
    topTrackStreams: 9713,
    topTrack: "Conditions",
    status: "qualifies",
    signal: "London-based songwriter and producer. Playing tiny local venues (Morocco Bound, Bermondsey). About as pre-fame as it gets.",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },
  {
    name: "Lagrace",
    genre: "Afro-Pop",
    monthlyListeners: 5073,
    topTrackStreams: 637866,
    topTrack: "Kombo Mabé",
    status: "qualifies",
    signal: "Congolese/Lingala-language afro-pop. Bio references being name-checked by ROSALÍA. Very early stage.",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },
  {
    name: "Seago",
    genre: "Alt-Pop",
    monthlyListeners: 44323,
    topTrackStreams: 2148915,
    topTrack: "Cheapshot",
    status: "established",
    signal: "44K monthly listeners (would qualify) but top track has 2.1M streams — over the cap. Featured on Pigeons & Planes 'Fresh Finds: Class of 2023.'",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },
  {
    name: "kerri",
    genre: "Alt-Pop",
    monthlyListeners: 83380,
    topTrackStreams: 4112316,
    topTrack: "dead / gone",
    status: "established",
    signal: "83K monthly listeners (would qualify) but top track has 4.1M streams — over the cap.",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },
  {
    name: "emma who?",
    genre: "Pop",
    monthlyListeners: 195676,
    topTrackStreams: 1823643,
    topTrack: "Hollow",
    status: "established",
    signal: "196K monthly listeners, top track 1.8M streams.",
    source: "SongsBrew — RADAR",
    sourceUrl: "https://songsbrew.com/radar",
    checkedAt: "2026-08-19"
  },

  // ---- Established: monthly listeners under 100K, but top track exceeds 1M streams ----
  {
    name: "Esme Emerson",
    genre: "Indie Pop",
    monthlyListeners: 45149,
    topTrackStreams: 1207810,
    topTrack: "Show You (Truck Song)",
    status: "established",
    signal: "45K monthly listeners (would qualify) but top track has 1.2M streams — over the cap. British-Chinese duo, touring with Hovvdy.",
    source: "Notion Magazine — Undiscovered #308",
    sourceUrl: "https://notion.online/undiscovered-308-humble-the-great-pretty-sick-esme-emerson-starcleaner-reunion/",
    spotifyUrl: "https://open.spotify.com/artist/6Jaz8RyF3F9ktK4aVFgbTL",
    checkedAt: "2026-08-18"
  },
  {
    name: "Namasenda",
    genre: "Synth-Pop",
    monthlyListeners: 225951,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "226K monthly listeners. Swedish, former PC Music affiliate.",
    source: "Hear Hear (Substack) — Essential Summer 2026 playlists",
    sourceUrl: "https://hearhear.substack.com/p/essential-summer-2026-playlists",
    spotifyUrl: "https://open.spotify.com/artist/5T68nryXXOMNE2kVe61fKX",
    checkedAt: "2026-08-18"
  },
  {
    name: "Mack Keane",
    genre: "Pop",
    monthlyListeners: 911068,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "911K monthly listeners — nearly 1M, too far along.",
    source: "One Write Music (Substack) — 'Wide Eyed' review",
    sourceUrl: "https://onewritemusic.substack.com/archive",
    spotifyUrl: "https://open.spotify.com/artist/7fNI5DhplKeFCErRvzRCVO",
    checkedAt: "2026-08-18"
  },
  {
    name: "Hannah Cole",
    genre: "Pop / Fuzz-Pop",
    monthlyListeners: 72112,
    topTrackStreams: 1286121,
    topTrack: "Massachusetts",
    status: "established",
    signal: "72K monthly listeners (would qualify) but top track has 1.29M streams — over the cap. Also already professionally managed (mgmt contact listed in Spotify bio).",
    source: "One Write Music (Substack)",
    sourceUrl: "https://onewritemusic.substack.com/archive",
    spotifyUrl: "https://open.spotify.com/artist/3XRj6XMmub9546oUagEqHY",
    checkedAt: "2026-08-18"
  },
  {
    name: "Carter Benjamin",
    genre: "Pop",
    monthlyListeners: 40213,
    topTrackStreams: 2844668,
    topTrack: "Sticks n' Stones",
    status: "established",
    signal: "40K monthly listeners (would qualify) but top track has 2.8M streams — over the cap. One viral breakout track, rest of catalog small.",
    source: "One Write Music (Instagram)",
    sourceUrl: "https://onewritemusic.substack.com/",
    spotifyUrl: "https://open.spotify.com/artist/2mN6M9Kde408WNk0YrHnQn",
    checkedAt: "2026-08-18"
  },

  // ---- Established: too big on monthly listeners ----
  {
    name: "Babe Dylan",
    genre: "Alt-Pop",
    monthlyListeners: 155226,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "155K monthly listeners. Mysterious duo, MGMT-adjacent sound, 'industry plant' speculation — unusually fast, well-funded rollout.",
    source: "Hear Hear (Substack)",
    sourceUrl: "https://hearhear.substack.com/p/7-rising-artists-to-know-in-2026",
    spotifyUrl: "https://open.spotify.com/artist/0xd16ai4mtpBCnoaAHCw1a",
    checkedAt: "2026-08-18"
  },
  {
    name: "SOFIA ISELLA",
    genre: "Pop",
    monthlyListeners: 932963,
    topTrackStreams: 25391285,
    topTrack: "Hot Gum",
    status: "established",
    signal: "932K monthly listeners, top track 25.4M streams. Already touring internationally.",
    source: "Pigeons and Planes",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/40Aif8AfzbNGA2s52ESEE2",
    checkedAt: "2026-08-18"
  },
  {
    name: "Sophia Stel",
    genre: "Pop",
    monthlyListeners: 770037,
    topTrackStreams: 11815605,
    topTrack: "I'll Take It",
    status: "established",
    signal: "770K monthly listeners, top track 11.8M streams. Touring the PC Music/hyperpop circuit with A.G. Cook, Hudson Mohawke.",
    source: "Pigeons and Planes",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/18w9tq3c2x11niEFNYqeex",
    checkedAt: "2026-08-18"
  },
  {
    name: "Lexa Gates",
    genre: "Pop",
    monthlyListeners: 231556,
    topTrackStreams: 9069291,
    topTrack: "Rotten To The Core",
    status: "established",
    signal: "231K monthly listeners, top track 9M streams. Touring theaters/arenas supporting Ravyn Lenae.",
    source: "Pigeons and Planes",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/5D70nuec9omH4CXmCGXGTu",
    checkedAt: "2026-08-18"
  },
  {
    name: "Natanya",
    genre: "Pop",
    monthlyListeners: 351656,
    topTrackStreams: 2185734,
    topTrack: "Sofa Joy",
    status: "established",
    signal: "351K monthly listeners. Headlining her own tour across Europe and North America.",
    source: "Pigeons and Planes",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/4QlEFh3gBGqmboPVc7AwUp",
    checkedAt: "2026-08-18"
  },
  {
    name: "Liim",
    genre: "Pop",
    monthlyListeners: 186307,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "186K monthly listeners. 22, Harlem/Brooklyn, Gucci & Supreme campaigns, upcoming album, major festival bookings (C2C Turin).",
    source: "Pigeons and Planes",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/4WBs3HlXxMAqo8Yi6m1PCM",
    checkedAt: "2026-08-18"
  },
  {
    name: "Haute & Freddy",
    genre: "Pop",
    monthlyListeners: 1040923,
    topTrackStreams: 12689054,
    topTrack: "Shy Girl",
    status: "established",
    signal: "Over 1M monthly listeners, 32-date North American headline tour. Confirms Spotify's own 'Artists to Watch' picks are already substantial.",
    source: "Spotify Newsroom",
    sourceUrl: "https://newsroom.spotify.com/2026-01-12/artists-to-watch-2026/",
    spotifyUrl: "https://open.spotify.com/artist/66T34XqGkEWbzKWALSBDuR",
    checkedAt: "2026-08-18"
  },
  {
    name: "Baby Nova",
    genre: "Pop",
    monthlyListeners: 656157,
    topTrackStreams: 1368909,
    topTrack: "Dodge",
    status: "established",
    signal: "656K monthly listeners.",
    source: "Spotify Newsroom",
    sourceUrl: "https://newsroom.spotify.com/2026-01-12/artists-to-watch-2026/",
    spotifyUrl: "https://open.spotify.com/artist/2dvThKiNFqpd5CVFCtJuFf",
    checkedAt: "2026-08-18"
  },
  {
    name: "Noah Rinker",
    genre: "Pop",
    monthlyListeners: 3331152,
    topTrackStreams: 63186073,
    topTrack: "Save My Soul",
    status: "established",
    signal: "3.3M monthly listeners, top track 63M streams. Playing the Ryman Auditorium.",
    source: "Spotify Newsroom",
    sourceUrl: "https://newsroom.spotify.com/2026-01-12/artists-to-watch-2026/",
    spotifyUrl: "https://open.spotify.com/artist/7Iz5t3KpNWPtB2uB2YyeN6",
    checkedAt: "2026-08-18"
  },
  {
    name: "Mikayla Geier",
    genre: "Pop",
    monthlyListeners: 379458,
    topTrackStreams: 12376279,
    topTrack: "piano in the sky",
    status: "established",
    signal: "379K monthly listeners, top track 12.4M streams.",
    source: "Spotify Newsroom",
    sourceUrl: "https://newsroom.spotify.com/2026-01-12/artists-to-watch-2026/",
    spotifyUrl: "https://open.spotify.com/artist/3L7svRFWE5kcIReq1uwC5J",
    checkedAt: "2026-08-18"
  },
  {
    name: "Alessi Rose",
    genre: "Alt-Pop",
    monthlyListeners: 338845,
    topTrackStreams: 10981531,
    topTrack: "oh my",
    status: "established",
    signal: "338K monthly listeners. Playing festivals alongside Lorde and Zara Larsson.",
    source: "BBC Sound of 2026",
    sourceUrl: "https://www.officialcharts.com/chart-news/bbc-sound-of-2026-nominees/",
    spotifyUrl: "https://open.spotify.com/artist/6QXtidyXX0uGggafrYdktx",
    checkedAt: "2026-08-18"
  },
  {
    name: "Chloe Qisha",
    genre: "Pop",
    monthlyListeners: 790555,
    topTrackStreams: 9923011,
    topTrack: "21st Century Cool Girl",
    status: "established",
    signal: "790K monthly listeners. Playing Reading & Leeds and Austin City Limits.",
    source: "BBC Sound of 2026",
    sourceUrl: "https://www.officialcharts.com/chart-news/bbc-sound-of-2026-nominees/",
    spotifyUrl: "https://open.spotify.com/artist/1WNmfSqydnt1FDJKg3l6lw",
    checkedAt: "2026-08-18"
  },
  {
    name: "Florence Road",
    genre: "Pop",
    monthlyListeners: 2564950,
    topTrackStreams: 23731360,
    topTrack: "Hanging Out To Dry",
    status: "established",
    signal: "2.56M monthly listeners. Playing Reading, Leeds, and Rock en Seine.",
    source: "BBC Sound of 2026",
    sourceUrl: "https://www.clashmusic.com/news/bbc-radio-1s-sound-of-2026-longlist-revealed/",
    spotifyUrl: "https://open.spotify.com/artist/0zzKEeF2bAVKrWeKc9CyJV",
    checkedAt: "2026-08-18"
  },
  {
    name: "Sasha Keable",
    genre: "Pop / R&B",
    monthlyListeners: 1885353,
    topTrackStreams: 37264850,
    topTrack: "NIGHT OFF",
    status: "established",
    signal: "1.88M monthly listeners, top track 37M streams. Major feature credits, playing ACL Festival.",
    source: "BBC Sound of 2026",
    sourceUrl: "https://www.clashmusic.com/news/bbc-radio-1s-sound-of-2026-longlist-revealed/",
    spotifyUrl: "https://open.spotify.com/artist/7MxGWmiAbqjNOGmj23wbWf",
    checkedAt: "2026-08-18"
  },
  {
    name: "AKRIILA",
    genre: "Pop / Reggaeton",
    monthlyListeners: 3111505,
    topTrackStreams: 55581991,
    topTrack: "Llora Llora",
    status: "established",
    signal: "3.1M monthly listeners, top track 55.6M streams. 26-date European tour.",
    source: "Popdust",
    sourceUrl: "https://www.popdust.com/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/39hfuTf4PHfnHgIl0QBDGL",
    checkedAt: "2026-08-18"
  },
  {
    name: "Moody Joody",
    genre: "Pop",
    monthlyListeners: 322974,
    topTrackStreams: 4573555,
    topTrack: "Velvet Connection",
    status: "established",
    signal: "322K monthly listeners. Playing 8123 Fest with The Maine, The Band CAMINO.",
    source: "Tuned Up",
    sourceUrl: "https://www.iamtunedup.com/tuned-ups-2026-breakout-artist-predictions/",
    spotifyUrl: "https://open.spotify.com/artist/0ndpuECxVStTsHhzq4Euxz",
    checkedAt: "2026-08-18"
  },
  {
    name: "Grace Ives",
    genre: "Electro-Pop",
    monthlyListeners: 528480,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "528,480 monthly listeners. Already touring with Robyn, Bleachers, Gracie Abrams.",
    source: "Hear Hear (Substack)",
    sourceUrl: "https://hearhear.substack.com/p/7-rising-artists-to-know-in-2026",
    spotifyUrl: "https://open.spotify.com/artist/4TZieE5978SbTInJswaay2",
    checkedAt: "2026-08-18"
  },
  {
    name: "Sarah Kinsley",
    genre: "Dream Pop",
    monthlyListeners: null,
    topTrackStreams: 61000000,
    topTrack: "breakout single",
    status: "established",
    signal: "Breakout single has ~61M streams — well over the 1M cap.",
    source: "Hear Hear (Substack)",
    sourceUrl: "https://hearhear.substack.com/p/7-rising-artists-to-know-in-2026",
    checkedAt: "2026-08-18"
  },
  {
    name: "Lay Bankz",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "Already proven TikTok algorithm command + real chart traction. Positioned for full breakout, too far along.",
    source: "Billboard",
    sourceUrl: "https://www.billboard.com/pro/major-label-viral-artist-signings-tiktok-cooling-off/",
    checkedAt: null
  },
  {
    name: "Adore",
    genre: "Electronic Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "'did i tell u that i miss u' has hit hundreds of millions of streams.",
    source: "Rolling Stone UK",
    sourceUrl: "https://www.rollingstone.co.uk/music/rolling-stone-uk-future-of-music-2026-full-list-61467/",
    checkedAt: null
  },
  {
    name: "ADÉLA",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "Already signed to Capitol/Polydor after 'The Debut: Dream Academy'; collabs with Grimes, Dylan Brady.",
    source: "Variety",
    sourceUrl: "https://variety.com/2026/film/news/tate-mcrae-sombr-tyriq-withers-power-of-young-hollywood-1236810170/",
    checkedAt: null
  },
  {
    name: "Skye Newman",
    genre: "Pop / Soul",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "BBC Sound of 2026 winner. Four Official Singles Chart hits already.",
    source: "BBC / DIY Magazine",
    sourceUrl: "https://diymag.com/news/skye-newman-winner-bbc-radio-1-sound-of-2026",
    checkedAt: null
  },
  {
    name: "Olivia Dean",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "2026 Grammy Best New Artist winner. No. 1 on Billboard Pop Airplay.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "sombr",
    genre: "Alt-Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "2026 Grammy Best New Artist nominee. 'Back to Friends' was a Hot 100 top-10, charted 52 weeks.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "KATSEYE",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "2026 Grammy Best New Artist + Best Pop Duo/Group nominee.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "Addison Rae",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "2026 Grammy Best New Artist nominee.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "Alex Warren",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "2026 Grammy Best New Artist nominee. 'Ordinary' was a record-breaking hit.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "Lola Young",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "2026 Grammy Best New Artist nominee.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "Audrey Hobert",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "Debut album peaked at #40 Billboard Hot 100. Sold-out tour.",
    source: "Popdust",
    sourceUrl: "https://www.popdust.com/artists-to-watch-2026",
    checkedAt: null
  },
  {
    name: "Tate McRae",
    genre: "Pop",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "Variety Power of Young Hollywood 2026, Triple Threat Award. 20.8B+ overall streams.",
    source: "Variety",
    sourceUrl: "https://variety.com/2026/film/news/tate-mcrae-sombr-tyriq-withers-power-of-young-hollywood-1236810170/",
    checkedAt: null
  },
  {
    name: "Chanpan",
    genre: "Pop",
    monthlyListeners: 283580,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "284K monthly listeners. Already covered by Vogue, CNN, HBO, Billboard.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/1fWoiW6kTjrVDoRc4ba3kh",
    checkedAt: "2026-08-18"
  },
  {
    name: "Tia Gordon",
    genre: "Bedroom Pop",
    monthlyListeners: 467624,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "468K monthly listeners. Touring UK/France (Jazz Cafe London).",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/5rXNmuTfaGC8hw0JEQOpLc",
    checkedAt: "2026-08-18"
  },
  {
    name: "Radio Free Alice",
    genre: "Pop / Rock",
    monthlyListeners: 469819,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "470K monthly listeners. Playing Reading Festival, Riot Fest, and major European festivals with Twenty One Pilots, Lorde.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/4cCA6V2DRIDqeYDyGIcEoj",
    checkedAt: "2026-08-18"
  },
  {
    name: "Gabriel Jacoby",
    genre: "R&B / Neo-Soul",
    monthlyListeners: 590252,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "590K monthly listeners. Playing Austin City Limits.",
    source: "Pigeons and Planes / Hear Hear",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/05pLxSVIyZiQTqQnR4QQ9H",
    checkedAt: "2026-08-18"
  },
  {
    name: "Deki Alem",
    genre: "Pop",
    monthlyListeners: 226716,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "227K monthly listeners. Opening for Swedish House Mafia at Ullevi Stadium.",
    source: "Hear Hear (Substack) / Pigeons and Planes",
    sourceUrl: "https://hearhear.substack.com/p/essential-summer-2026-playlists",
    spotifyUrl: "https://open.spotify.com/artist/2AK3F4tVjxYuqSGefozy52",
    checkedAt: "2026-08-18"
  },
  {
    name: "Saya Gray",
    genre: "Alt-Pop / R&B",
    monthlyListeners: 934238,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "934K monthly listeners. Playing a festival with Turnstile and Yves Tumor.",
    source: "Hear Hear (Substack) — Essential Summer 2026 playlists",
    sourceUrl: "https://hearhear.substack.com/p/essential-summer-2026-playlists",
    spotifyUrl: "https://open.spotify.com/artist/4EnymklUyqZwvmHQGlRssl",
    checkedAt: "2026-08-18"
  },
  {
    name: "TOMORA",
    genre: "Euro Club / Pop",
    monthlyListeners: 411015,
    topTrackStreams: null,
    topTrack: null,
    status: "established",
    signal: "411K monthly listeners. Duo of AURORA + Tom Rowlands (Chemical Brothers) — already major names, playing National Stadium Dublin and the Roundhouse.",
    source: "Hear Hear (Substack) — Essential Summer 2026 playlists",
    sourceUrl: "https://hearhear.substack.com/p/essential-summer-2026-playlists",
    spotifyUrl: "https://open.spotify.com/artist/5r0BuurxKQugj8cjHiO8pY",
    checkedAt: "2026-08-18"
  },

  // ---- Off genre: doesn't fit pop, regardless of size ----
  {
    name: "The Marías",
    genre: "Psychedelic Soul",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "off_genre",
    signal: "Psychedelic soul, not pop. Also a 2026 Grammy Best New Artist nominee — too big regardless.",
    source: "Grammy.com",
    sourceUrl: "https://www.grammy.com/news/2026-grammys-nominations-best-new-artist/",
    checkedAt: null
  },
  {
    name: "EsDeeKid",
    genre: "UK Rap",
    monthlyListeners: null,
    topTrackStreams: null,
    topTrack: null,
    status: "off_genre",
    signal: "UK rap, not pop. Also one of 2025's most significant breakout British artists — too big regardless.",
    source: "Tuned Up",
    sourceUrl: "https://www.iamtunedup.com/tuned-ups-2026-breakout-artist-predictions/",
    checkedAt: null
  },
  {
    name: "Zukenee",
    genre: "Trap / Rap",
    monthlyListeners: 339611,
    topTrackStreams: null,
    topTrack: null,
    status: "off_genre",
    signal: "Trap/rap, not pop — opening for Yeat. 340K monthly listeners too, for reference.",
    source: "Pigeons and Planes",
    sourceUrl: "https://www.pigeonsandplanes.com/read/artists-to-watch-2026",
    spotifyUrl: "https://open.spotify.com/artist/3FFfAZsrsx8ot1m6H5vzQc",
    checkedAt: "2026-08-18"
  },
  {
    name: "Wynona Bleach",
    genre: "Shoegaze / Alt-Rock",
    monthlyListeners: 846,
    topTrackStreams: null,
    topTrack: null,
    status: "off_genre",
    signal: "Shoegaze/alt-rock, not pop — and already signed to Fierce Panda Records.",
    source: "Notion Magazine — Undiscovered",
    sourceUrl: "https://notion.online/tag/undiscovered/",
    spotifyUrl: "https://open.spotify.com/artist/3U7XDjbMZWVbis1wAUzjMq",
    checkedAt: "2026-08-18"
  },
  {
    name: "Slow Fiction",
    genre: "Shoegaze / Dream Pop",
    monthlyListeners: 73428,
    topTrackStreams: 63204,
    topTrack: "junior year",
    status: "off_genre",
    signal: "Would qualify numerically, but is shoegaze/dream-pop, not pop — touring with Swervedriver.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/3ZyjpHbSpzsLV3ZEyJZBAW",
    checkedAt: "2026-08-18"
  },
  {
    name: "Honest Work",
    genre: "Alt-Rock / Grunge",
    monthlyListeners: 2262,
    topTrackStreams: null,
    topTrack: null,
    status: "off_genre",
    signal: "FFO Smashing Pumpkins, REM, Alice In Chains. Not pop.",
    source: "DIY Magazine — The Neu Bulletin",
    sourceUrl: "https://diymag.com/neu",
    spotifyUrl: "https://open.spotify.com/artist/3n9jB3AymRSh9peJBrihrx",
    checkedAt: "2026-08-18"
  }
];
